version: '3'
services:
  mongo-express:
    image: mongo-express:0.54
    links:
      - "mongo-service:mongo"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
    volumes:
      - mongodb-data
  mongo-service:
    image: mongo:4.1.6
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
